Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using project5.Models;

namespace project5.Controllers
{
	[Authorize(Roles ="admin")]
    public class CategoryController : Controller
	{
		private readonly DataContext _context;
		public CategoryController(DataContext context)
		{ _context = context; }

		public IActionResult Index(string srchStr, string SortOrder, int? pageNo)
		{
			ViewData["currentSort"] = SortOrder;
			ViewData["IDsort"] = SortOrder == "idAsc" ? "idDsc" : "idAsc";
			ViewData["Namesort"] = SortOrder == "nameAsc" ? "nameDsc" : "nameAsc";
			ViewData["Dessort"] = SortOrder == "desAsc" ? "desDsc" : "desAsc";
			var categories = _context.Categories.AsQueryable();

			if (!string.IsNullOrEmpty(srchStr))
			{
				ViewData["search"] = srchStr;
				categories = categories.Where(p => p.CategoryName.ToLower().Contains(srchStr.ToLower()) ||
											p.CategoryDescription.ToLower().Contains(srchStr.ToLower()));

			}


			switch (SortOrder) {
				case "idAsc":
					categories = categories.OrderBy(p => p.ID);
					break;
				case "idDsc":
					categories = categories.OrderByDescending(p => p.ID);
					break;
				case "nameAsc":
					categories = categories.OrderBy(p => p.CategoryName);
					break;
				case "nameDsc":
					categories = categories.OrderByDescending(p => p.CategoryName);
					break;
				case "desAsc":
					categories = categories.OrderBy(p => p.CategoryDescription);
					break;
				case "desDsc":
					categories = categories.OrderByDescending(p => p.CategoryDescription);
					break;
			}

			int pageSize = 5;
			ViewData["pageNo"] = pageNo ?? 1;
			var paginated = PaginatedList<Category>.getlist(categories.ToList(), pageNo ?? 1, pageSize);
			return View(paginated);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(Category category)
		{
			_context.Categories.Add(category);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		[HttpGet("/Category/Delete/{id}")]
        public async Task<IActionResult> Delete(long id)
        {
			var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }


    }
}

Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using project5.Models;
using System.Security.Claims;

namespace project5.Controllers
{
    public class ReviewController : Controller
	{
		private readonly DataContext _context;

		public ReviewController(DataContext context)
		{
			_context = context;
		}

		public IActionResult Index(string sortOrder ,int? pageNo)
		{
            ViewData["currentSort"] = sortOrder;
            ViewData["IDsort"] = sortOrder == "idAsc" ? "idDsc" : "idAsc";
            ViewData["Namesort"] = sortOrder == "nameAsc" ? "nameDsc" : "nameAsc";
            ViewData["titlesort"] = sortOrder == "titleAsc" ? "titleDsc" : "titleAsc";
			ViewData["dessort"] = sortOrder == "desAsc" ? "desDsc" : "desAsc";
			ViewData["ratingsort"] = sortOrder == "ratingAsc" ? "ratingDsc" : "ratingAsc";
			ViewData["contentsort"] = sortOrder == "contentAsc" ? "contentDsc" : "contentAsc";

			var reviews = _context.Reviews.Include(p => p.Content).Include(p => p.ReviewerName).AsQueryable();

			if (User.IsInRole("user"))
            {
                reviews = reviews.Where(p => p.userID == User.FindFirstValue(ClaimTypes.NameIdentifier));
            }

			
           

            switch (sortOrder)
            {
                case "idAsc":
                    reviews = reviews.OrderBy(p => p.ReviewId);
                    break;
                case "idDsc":
                    reviews = reviews.OrderByDescending(p => p.ReviewId);
                    break;
                case "nameAsc":
                    reviews = reviews.OrderBy(p => p.ReviewerName.UserName);
                    break;
                case "nameDsc":
                    reviews = reviews.OrderByDescending(p => p.ReviewerName.UserName);
                    break;
                case "desAsc":
                    reviews = reviews.OrderBy(p => p.ReviewDescription);
                    break;
                case "desDsc":
                    reviews = reviews.OrderByDescending(p => p.ReviewDescription);
                    break;
                case "titleAsc":
                    reviews = reviews.OrderBy(p => p.ReviewTitle);
                    break;
                case "titleDsc":
                    reviews = reviews.OrderByDescending(p => p.ReviewTitle);
                    break;
                case "ratingAsc":
                    reviews = reviews.OrderBy(p => p.Rating);
                    break;
                case "ratingDsc":
                    reviews = reviews.OrderByDescending(p => p.Rating);
                    break;
                case "contentAsc":
                    reviews = reviews.OrderBy(p => p.Rating);
                    break;
                case "contentDsc":
                    reviews = reviews.OrderByDescending(p => p.Rating);
                    break;
            }

            int pageSize = 5;
            ViewData["pageNo"] = pageNo ?? 1;
            var paginated = PaginatedList<Review>.getlist(reviews.ToList(), pageNo ?? 1, pageSize);
            return View(paginated); 
		}

		[HttpGet]
		public IActionResult Create(int id)
		{
            ViewBag.Id = id;
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(Review review)
		{
            review.userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
			_context.Reviews.Add(review);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

        [HttpGet("/Review/Delete/{id}")]
        public async Task<IActionResult> Delete(long id)
		{
			var review = await _context.Reviews.FindAsync(id);
			_context.Reviews.Remove(review);
			await _context.SaveChangesAsync();
			return RedirectToAction("Index");

		}

	}
}

Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - MyWebApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        nav {
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); 
            
        }

        .navbar-brand {
            font-weight: bold;
            font-size: 1.8rem;
            color: #007bff;
        }

        .navbar-brand:hover {
            color: #0056b3;
        }

        .navbar-nav {
            display: flex;
            flex-direction: row;
            align-items: center;
        }

        .navbar-nav .nav-item {
            margin-right: 15px;
        }

        
        .form-inline .input-group {
            width: 300px; 
        }

        .nav-form-control {
            padding-left: 35px; 
            border-radius: 30px; 

        
        .btn-outline-secondary {
            border-radius: 30px; 
            background-color: #007bff;
            color: white;
        }

        .btn-outline-secondary:hover {
            background-color: #0056b3;
        }

        .nav-link i {
            font-size: 1.5rem;
            transition: transform 0.2s ease-in-out;
        }

        .nav-link:hover i {
            transform: scale(1.2);
        }

        .nav-item .login {
            font-size: 1.5rem;
        }

        .container {
            margin-top: 20px;
        }
            
    </style>
</head>
<body>
   
    <nav class="navbar navbar-light bg-light justify-content-between">
        <a class="navbar-brand">cineVerse</a>
        
      
       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-filter="all" >Home</a></li>
            <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-filter="Movie">Movies</a></li>
            <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-filter="Anime">Animes</a></li>
            <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-filter="Series">Series</a></li>
            @if(User.Identity.IsAuthenticated)
            {
                <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Review" >Reviews</a></li>
                if(User.IsInRole("admin"))
                {
                    <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="Category">Categories</a></li>
                }
                
            }

</ul>

       
        <form class="form-inline d-flex" action="/search" method="get">
            <div class="input-group">
                <input class="nav-form-control" type="search" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-secondary" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </form>

        
         <ul class="navbar-nav ms-auto">
            <li class="nav-item">

                @if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                        <div class="d-flex align-items-center">
                            <span class="navbar-text me-3 ">
                                <i class="fas fa-user"></i> Hoşgeldin, @User.Identity.Name
                            </span>
                            <a class="nav-link-primary" style="text-decoration: none;" asp-controller="Account"
                                asp-action="LogOut">
                                Log Out
                            </a>
                        </div>
                }
                else
                {
                        <a class="nav-link-primary login" style="text-decoration: none;" asp-action="LogIn"
                            asp-controller="Account">
                            <i class="fas fa-sign-in-alt"></i> Log In
                        </a>
                }
            </li>
        </ul>
    </nav>


    <div class="container mt-4">
        @RenderBody()

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)


</body>
</html>



    